#!/bin/sh

#nstall Ruby and Gem

#Install Jekyll and Bundler
sudo gem install jekyll bundler

git clone https://github.com/apache/servicecomb-website.git

#Install the gems with bundle
sudo bundle install

#Run the following command to install GitBook
npm install gitbook-cli -g
