#!/bin/bash


git clone https://github.com/apache/servicecomb-docs.git

gitbook build incubator-servicecomb-docs/java-chassis-reference users/servicecomb-java-chassis-doc
 
bundle exec jekyll build --config _config.yml

bundle exec jekyll server --port 4000 --host 
