#!/bin/bash

script_dir=$(cd `dirname $0`; pwd)
echo cru$script_dir
base_dir=`dirname ${script_dir}`
echo build $base_dir
cd ${base_dir}
sudo bundle exec jekyll build --config _config.yml
sudo bundle exec jekyll server --port 4000 --host 
